SET IDENTITY_INSERT [dbo].[HighSchoolCourses] ON 

INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6000, N'Math 30-1')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6001, N'Math 30-2')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6002, N'Math 20-1')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6003, N'Math 20-2')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6004, N'Math 31')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6005, N'Math 33')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6006, N'Math 13')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6007, N'Math 10-2')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6008, N'Math 10-1')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6009, N'Math 10C')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6010, N'English 30-1')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6011, N'English 20-1')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6012, N'English 30-2')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6013, N'English 10-2')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6014, N'English 11')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6015, N'Science 20')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6016, N'Science 30')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6017, N'Science 11')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6018, N'Biology 30')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6019, N'Biology 20')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6020, N'Chemistry 30')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6021, N'Chemistry 20')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6022, N'Physics 30')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6023, N'Physics 20')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6024, N'Chemistry')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6025, N'Social Studies 30-1')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6026, N'Social Studies 11')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6027, N'Social Studies 12')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6028, N'Legal Studies 12')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6029, N'Post Secondary Sociology')
INSERT [dbo].[HighSchoolCourses] ([HighSchoolCourseID], [HighSchoolCourseName]) VALUES (6030, N'Post Secondary Psychology')