DELETE FROM NaitCourses
SET IDENTITY_INSERT [dbo].[NaitCourses] ON 

INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1001', N'Communications for Digital Media & IT', 3,1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('COMP1017', N'Web Design Fundamentals I', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('ORGB1500', N'Organizational Behaviour for Media and IT', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2000', N'Advanced Communication for Digital Media and IT', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2590', N'Capstone Project', 6, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1003', N'3D Modeling I', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1009', N'Digital Suite Technology', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1501', N'Rigging and Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1504', N'Audio for Games and Animation', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('COMP1008', N'Digital Graphic Design Tools', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1007', N'Character Design', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1013', N'Digital Content Story Development', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DSGN1016', N'Visual Communications I', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DSGN1527', N'Visual Communications II', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('VISA1515', N'Illustration Fundamentals', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2004', N'3D Animation II', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2005', N'Compositing and Visual Effects', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2006', N'Digital Sculpting', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2007', N'3D Natural Environments', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2502', N'2D Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2514', N'Production Planning and Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2024', N'Motion Graphics', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2031', N'Visual Communications III', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2501', N'Portfolio Development', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT2508', N'Cinematography for Games and Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('ANAP1525', N'Systems Analysis and Design I', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('CMIS1014', N'System Foundations', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('CPSC1012', N'Programming Fundamentals', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('CPSC1517', N'Introduction to Application Development', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1508', N'Database Fundamentals', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('ANAP1005', N'Analysis: Fundamental Methods', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1006', N'Business Practices', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseName], [CourseCredits],[Active]) VALUES ('DMIT1518', N'IT System Administration', 3, 1)