DELETE FROM NaitCourses
SET IDENTITY_INSERT [dbo].[NaitCourses] ON 

INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (1, 'DMIT1001', N'Communications for Digital Media & IT', 3,1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (2, 'COMP1017', N'Web Design Fundamentals I', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (3, 'ORGB1500', N'Organizational Behaviour for Media and IT', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (4, 'DMIT2000', N'Advanced Communication for Digital Media and IT', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (5, 'DMIT2590', N'Capstone Project', 6, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (6, 'DMIT1003', N'3D Modeling I', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (7, 'DMIT1009', N'Digital Suite Technology', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (8, 'DMIT1501', N'Rigging and Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (9, 'DMIT1504', N'Audio for Games and Animation', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (10, 'COMP1008', N'Digital Graphic Design Tools', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (11, 'DMIT1007', N'Character Design', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (12, 'DMIT1013', N'Digital Content Story Development', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (13,'DSGN1016', N'Visual Communications I', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (14,'DSGN1527', N'Visual Communications II', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (15,'VISA1515', N'Illustration Fundamentals', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (16, 'DMIT2004', N'3D Animation II', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (17, 'DMIT2005', N'Compositing and Visual Effects', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (18, 'DMIT2006', N'Digital Sculpting', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (19, 'DMIT2007', N'3D Natural Environments', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (20, 'DMIT2502', N'2D Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (21, 'DMIT2514', N'Production Planning and Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (22, 'DMIT2024', N'Motion Graphics', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (23, 'DMIT2031', N'Visual Communications III', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (24, 'DMIT2501', N'Portfolio Development', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (25, 'DMIT2508', N'Cinematography for Games and Animation', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (26, 'ANAP1525', N'Systems Analysis and Design I', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (27, 'CMIS1014', N'System Foundations', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (28, 'CPSC1012', N'Programming Fundamentals', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (29, 'CPSC1517', N'Introduction to Application Development', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (30, 'DMIT1508', N'Database Fundamentals', 4.5, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (31, 'ANAP1005', N'Analysis: Fundamental Methods', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (32, 'DMIT1006', N'Business Practices', 3, 1)
INSERT [dbo].[NaitCourses] ([CourseID], [CourseCode], [CourseName], [CourseCredits],[Active]) VALUES (33, 'DMIT1518', N'IT System Administration', 3, 1)